### ISSUE TITLE
Multifield sort issue

### ISSUE THREAD

**Issue by hazeltod** [DrHyde/perl-modules-Sort-MultipleFields#1]
When sorting by field Brand => "asc", then by field Key => "numasc", the field Brand became sorted case sensitive.  

My code:

sub sortData {
    my ( $mData, $fSpec ) = @_;	
    my $fSpecStr;  
    for ( my $i = 0; $i < @$fSpec; $i++ ) {
        if ( $fSpec->[$i] =~ /numasc|numascending|numdesc|numdescending/ ) {
	    $fSpecStr .= $fSpec->[$i] . ",\n";
	} elsif ( $fSpec->[$i] =~ /asc|ascending/ ) {
            $fSpec->[$i] =~ s/asc|ascending/sub { lc( \$_[0] ) cmp lc( \$_[1] ) }/g;
            $fSpec->[$i] =~ s/"|'//g;
	    $fSpecStr .= $fSpec->[$i] . ",\n";
	} else {
	    $fSpec->[$i] =~ s/desc|descending/sub { lc( \$_[1] ) cmp lc( \$_[0] ) }/g;
	    $fSpec->[$i] =~ s/"|'//g;
	    $fSpecStr .= $fSpec->[$i] . ",\n";
        }
    }
    my $sortSpec = mfsortmaker( sub { eval $fSpecStr } );
    my $sorted = [ sort $sortSpec @$mData ];
    return $sorted;
}

{ # Main

    # $mData is a reference to an array of a hash

    my $sorted = sortData( $mData,  [ 'Brand => "asc",
							     Key   => "numasc",'
							   ]
				          );
} # End Main

output follows:

586    Honda         6    Black             
589    Honda       6.5    Purple            
 35    Kawasaki     10    Blue              
580    Kawasaki      5    Black             
581    Kawasaki      8    Black             
583    Kawasaki      6    Black             
585    Kawasaki      6    Red               
587    Kawasaki      9    Black             
588    Kawasaki    6.5    Burgundy          
591    Kawasaki    6.5    Black             
941    Kawasaki    7.5    Burgundy          
946    Kawasaki      7    Burgundy          
950    Kawasaki      9    Gold              
977    Kawasaki      8    Silver            
979    Kawasaki     10    Black             
980    Kawasaki      9    Black             
999    Kawasaki      8    Silver            
628    Yamaha      7.5    Gold              
630    Yamaha      7.5    Black             
518    honda         7    Pewter            
582    honda         6    Black             
590    honda         8    Black             
584    kawasaki      6    Black             
594    kawasaki      7    Black             
595    kawasaki      7    Blue              
639    kawasaki      8    White             
640    kawasaki      8    Black             
641    kawasaki      8    Black             
642    kawasaki      8    Gray              
643    kawasaki      8    Black             
644    kawasaki    7.5    Black             
645    kawasaki      8    Burgundy          
650    kawasaki      8    Purple            
657    kawasaki    8.5    Black             
664    kawasaki    8.5    Gold              
596    yamaha        7    Black             
597    yamaha        5    Black             
618    yamaha      7.5    Black             

I do have a work around for this.  I simply pass in the multifield sorted ref into the single field sort.  For example, 

    my $sorted = sortData( $mData,  [ 'Brand => "asc",
							     Key   => "numasc",' # Multifield sort loses case insensitivity
							   ]
				          );
       $sorted = sortData( $sorted,  [ 'Brand => "asc"' ] );

Seems to work.  However, the work around should not be necessary.  If a fix is problematic, the work around is acceptable.  Just thought I'd bring this to your attention.

Thank you for your patience and consideration.

-Dave H.

**Comment by DrHyde** [comment]
That's odd, your work-around shouldn't work! ASCIIbetical sorting means sorting in ASCII order, so all upper-case letters come before lower-case. The fact that it does work is a bug. Could you let me know your locale settings so I can turn that into a test case?

I need to fix the ASCIIbetical sort, and then add a locale-sensitive sort option.

**Comment by DrHyde** [comment]
Actually ignore that. The problem is that you're passing this to your function: `$mdata, ['a string']`. Get rid of the single quotes and I think you'll get what you expect.
